parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['eus']
    - environmentName: 'tst'
      regionAbrvs: ['eus']
- name: templateFileName
  type: string
  default: 'main'
- name: templateDirectory
  type: string 
  default: 'infrastructure'
- name: serviceName
  type: string
  default: 'storageAccount1'
- name: bicepParamExt
  type: boolean
  default: true
stages:
- template: stages/bicep_build_stage.yml@templates
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    templateFileName: ${{ parameters.templateFileName }}
    serviceName: ${{ parameters.serviceName }}
    templateDirectory: ${{ parameters.templateDirectory }}
    bicepParamExt: ${{ parameters.bicepParamExt }}
    
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/bicep_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      templateFileName: ${{ parameters.templateFileName }}
      serviceName: ${{ parameters.serviceName }}
      templateDirectory: ${{ parameters.templateDirectory }}
      bicepParamExt: ${{ parameters.bicepParamExt }}
